name = "redbubble-ready"
main = "src/app/page.tsx"
compatibility_date = "2025-05-22"

[site]
bucket = "./out"

[build]
command = "npm run build"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


