name = "redbubble-ready"
main = "src/index.ts"
compatibility_date = "2025-05-22"

[build]
command = "npm run build"

[build.upload]
format = "modules"
main = "src/index.ts"

[[build.upload.rules]]
type = "CompiledJavaScript"
globs = ["**/*.js"]

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true


